name: Server Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      # Step 1: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} # Update this if your region is different
          # aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
          # ecr-repository-uri: ${{ secrets.ECR_REPOSITORY_URI }}
          # # ecr-repository-uri: ${{ secrets.ECR_REPOSITORY_URI }}
          # ecs-backend-service-name: ${{ secrets.ECS_BACKEND_SERVICE_NAME }}
          # ecs-cluster-name: ${{ secrets.ECS_CLUSTER_NAME }}

      # Step 2: Log in to Amazon ECR # docker build -t my-backend-app .

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Build and push Docker image
        run: |
          docker build -t  ${{ secrets.ECR_BACKEND_REPOSITORY_NAME }} .
          docker tag my-backend-app:latest ${{ secrets.ECR_REPOSITORY_URI }}
          docker push ${{ secrets.ECR_REPOSITORY_URI }}

      - name: Update ECS Service
        run: |
          aws ecs update-service --cluster ${{ secrets.ECS_CLUSTER_NAME }} --service ${{ secrets.ECS_BACKEND_SERVICE_NAME }} --force-new-deployment
