name: Client View React CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      # Step 1: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} # Update this if your region is different

      # Step 2: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-00 | docker login --username AWS --password-stdin 980921722238.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and push Docker image
        run: |
          docker build -t my-backend-app .
          docker tag my-backend-app:latest 980921722238.dkr.ecr.us-east-1.amazonaws.com/my-backend-app:latest
          docker push 980921722238.dkr.ecr.us-east-1.amazonaws.com/my-backend-app:latest

      - name: Update ECS Service
        run: |
          aws ecs update-service --cluster My-React-App-Cluster --service My-Backend-App-Service --force-new-deployment
